import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "../../../../components/theme-provider"
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/root/common/AppSiderbar";
import Header from "@/components/root/common/Header";
import { Toaster } from "@/components/ui/sonner"
const getPoppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Covertron Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className="h-full" suppressHydrationWarning>
      <head />
      <body
        className={`${getPoppins.className} antialiased flex flex-col min-h-screen bg-background dark:bg-backgroundDark`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex-grow pt-0">
            <SidebarProvider>
              <AppSidebar />
              <div className="w-full">
                <Header />
                <main className="w-full max-w-5xl mx-auto pt-6 sm:px-1 px-2">
                  {children}
                </main>
                <Toaster />
              </div>
            </SidebarProvider>
          </div>
        </ThemeProvider>
      </body>
    </html >
  );
}
