# 1. Imagen base ligera de Node
FROM node:20-alpine

# 2. Carpeta de trabajo
WORKDIR /app

# 3. Copiar package.json y package-lock.json
COPY package*.json ./

# 4. Instalar dependencias
RUN npm install

# 5. Copiar el resto del código
COPY . .


# 6. Puerto
EXPOSE 3000

# 7. Comando para desarrollo con hot reload
CMD ["npm", "run", "dev"]
