import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@/app/globals.css';
import Footer from '@/components/user/Footer';
import { ThemeProvider } from '../../components/theme-provider';
import Navbar from '@/components/user/Navbar';

const getPoppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: 'Covertron',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full scroll-smooth"
      suppressHydrationWarning
    >
      <head />
      <body
        className={`${getPoppins.className} antialiased flex flex-col min-h-screen bg-background scroll-smooth`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <main className="flex-grow w-full dark:bg-backgroundDark -mb-4">
            <div>{children}</div>
          </main>
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
